
-- USERS
DROP TABLE USERS;

SELECT * FROM USERS;

INSERT INTO USERS 
VALUES('CAT🐱', '010-3333-2222', 'SUNGSOO', 'EMAIL@NAVER.COM', 'USER'); 

CREATE TABLE USERS(
	ID VARCHAR2(20) NOT NULL,
	PHONE VARCHAR2(100) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	ROLE VARCHAR2(100) NOT NULL,
	
	CONSTRAINT USERS_ID_PK PRIMARY KEY(ID)
);

-- QNAS
DROP TABLE QNAS;
DROP SEQUENCE BOARDNO_SEQ;

SELECT * FROM QNAS;

INSERT INTO QNAS
VALUES('BEAR', 23, '어드민 콘텐츠', sysdate);
INSERT INTO QNAS
VALUES('BEAR', 25, 'can i help you?', sysdate);
INSERT INTO QNAS
VALUES('BEAR', 21, '안녕하세요 코로나 그린입니다. 실시간 차트를 원하실 경우 메인에서 확인 가능하며, 뉴스 및 정책은 하루에 한번씩 업데이트 되고 있습니다. 감사합니다.', sysdate);

CREATE SEQUENCE BOARDNO_SEQ;

CREATE TABLE QNAS(
	ID VARCHAR2(20) NOT NULL,
	BOARDNO NUMBER NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL,
	
	CONSTRAINT QNAS_BOARDNO_PK PRIMARY KEY(BOARDNO),
	FOREIGN KEY (ID) REFERENCES USERS(ID)
);

-- DONATION
DROP TABLE DONAS;

DROP SEQUENCE DONATION_SEQ;

CREATE SEQUENCE DONATION_SEQ;

CREATE TABLE DONAS(
	DONATIONORDER NUMBER NOT NULL,
	ID VARCHAR2(20) NOT NULL,
	PAYMENT NUMBER NOT NULL,
	REGDATE DATE NOT NULL,
	
	CONSTRAINT DONATION_ORDER_PK PRIMARY KEY(DONATIONORDER),
	FOREIGN KEY(ID) REFERENCES USERS(ID)
);

SELECT * FROM DONAS;
INSERT INTO DONAS VALUES(1, 'BEAR', 30000, SYSDATE);
INSERT INTO DONAS VALUES(5, 'CAT🐱', 9000, SYSDATE);
